### ISSUE TITLE
source command fails on w64devkit

### ISSUE THREAD

**Issue by a-n-d-a-i** [gtrxAC/gxbuild#5]
On w64devkit (busybox?) `source config.sh` does not work:
```
./setup.sh: source: line 14: config.sh: not found
```
After changing `source config.sh` to `source ./config.sh` in setup.sh and build.sh, everything worked fine.
(Note: the other `source` commands, e.g. `source android/setup.sh` worked fine, do not need to be modified.)

**Comment by gtrxAC** [comment]
Fixed, thanks for reporting.
